### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by FutureLights** [flyingrub/scdl#313]
When I run the command `scdl -l https://soundcloud.com/user -a"` I get this error `[WinError 2] The system cannot find the file specified` for most songs. After downloading +300 songs, I only had under 50 actually ones. The full error message is

    Tracks and reposts n°314 of 314
    Found a track
    Retrieving more info on the track
    Downloading The Land Of Eternal Winter
    [WinError 2] The system cannot find the file specified
    Traceback (most recent call last):
      File "c:\users\user\anaconda3\lib\site-packages\scdl\scdl.py", line 349, in download
        parse_url(uri)
      File "c:\users\user\anaconda3\lib\site-packages\scdl\scdl.py", line 263, in parse_url
        download_track(item)
      File "c:\users\user\anaconda3\lib\site-packages\scdl\scdl.py", line 546, in download_track
        filename = download_hls_mp3(track, title)
      File "c:\users\user\anaconda3\lib\site-packages\scdl\scdl.py", line 521, in download_hls_mp3
        subprocess.call(['ffmpeg', '-i', url, '-c', 'copy', filename_path, '-loglevel', 'fatal'])
      File "c:\users\user\anaconda3\lib\subprocess.py", line 323, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\users\user\anaconda3\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "c:\users\user\anaconda3\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

This is the exact command that I ran in case it's based on the user:

    scdl -l https://soundcloud.com/anttimartikainen -a --path "C:\Users\user\Music\Antti Martikainen"

I installed it just a couple of hours ago, so I'm not using an old version.

**Comment by Devonizzle** [comment]
Okay, it took me a months to figure out this problem as well, and I finally got the solution. Install ffmpeg from its website and then add its bin folder to your system variable path. Once done, **use default cmd terminal** not a downloadable terminal. This should resolve the problem.

**Comment by FutureLights** [comment]
> Okay, it took me a months to figure out this problem as well, and I finally got the solution. Install ffmpeg from its website and then add its bin folder to your system variable path. Once done, **use default cmd terminal** not a downloadable terminal. This should resolve the problem.

Thanks!

**Comment by Anthony-de-cruz** [comment]
Doesn't appear to have resolved the issue for me, I've got the same thing.

**Comment by flyingrub** [comment]
You have to add ffmpeg's bin folder to PATH

**Comment by inzru** [comment]
I added the ffmpeg bin folder to path and I still can't install the SC downloader.  This is my error message:

```
Collecting git+https://github.com/flyingrub/scdl
  Cloning https://github.com/flyingrub/scdl to c:\users\ivanm\appdata\local\temp\pip-req-build-u1v_7_k_
  Running command git clone -q https://github.com/flyingrub/scdl 'C:\Users\ivanm\AppData\Local\Temp\pip-req-build-u1v_7_k_'
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/flyingrub/scdl 'C:\Users\ivanm\AppData\Local\Temp\pip-req-build-u1v_7_k_'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

**Comment by flyingrub** [comment]
Well the error is pretty self explanatory, isn't it ? 
`ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?`

**Comment by RB04** [comment]
I added bin to PATH and still get the same error, used Python 9 and didn't worked, neither for the updated one
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python36-32\Scripts\scdl-script.py", line 11, in <module>
    load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()
  File "c:\users\XXXX\appdata\local\programs\python\python36-32\lib\site-packages\scdl\scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "c:\users\XXXX\appdata\local\programs\python\python36-32\lib\site-packages\scdl\scdl.py", line 280, in parse_url
    download_playlist(item)
  File "c:\users\XXXX\appdata\local\programs\python\python36-32\lib\site-packages\scdl\scdl.py", line 413, in download_playlist
    download_track(track_raw, playlist_info)
  File "c:\users\XXXX\appdata\local\programs\python\python36-32\lib\site-packages\scdl\scdl.py", line 579, in download_track
    filename, is_already_downloaded = download_hls_mp3(track, title)
  File "c:\users\XXXX\appdata\local\programs\python\python36-32\lib\site-packages\scdl\scdl.py", line 548, in download_hls_mp3
    subprocess.call(['ffmpeg', '-i', url, '-c', 'copy', filename_path, '-loglevel', 'fatal'])
  File "c:\users\XXXX\appdata\local\programs\python\python36-32\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\XXXX\appdata\local\programs\python\python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\users\XXXX\appdata\local\programs\python\python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
