### ISSUE TITLE
StopIteration Exception in is_client_id_valid()

### ISSUE THREAD

**Issue by 0pcom** [flyingrub/scdl#470]
installed soundcloud-dl-git from AUR (archlinux)

soundcloud-dl-git  v2.7.5.r0.ge8a0f92-1

```
$ scdl -tl https://soundcloud.com/kind
Soundcloud Downloader
Traceback (most recent call last):
  File "/usr/bin/scdl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/scdl/scdl.py", line 158, in main
    if not client.is_client_id_valid():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/soundcloud/soundcloud.py", line 125, in is_client_id_valid
    next(
StopIteration


$ scdl -l https://soundcloud.com/kind/begin-again-kindtide-flip
Soundcloud Downloader
Traceback (most recent call last):
  File "/usr/bin/scdl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/scdl/scdl.py", line 158, in main
    if not client.is_client_id_valid():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/soundcloud/soundcloud.py", line 125, in is_client_id_valid
    next(
StopIteration


```

This was working before I updated recently.

**Comment by CosmicSage** [comment]
That's right. I never updated the tool, yet the problem has popped up. The issue lays in [https://github.com/7x11x13/soundcloud.py](in the soundcloud API wrapper used by the tool). Sadly the Moderator is mega cucked to update it or even merge PRs so look out  for my fork I will try to fix. Seems Soundcloud changed something there end.

**Comment by adithayyil** [comment]
The issue was fixed recently. prob not updated in the AUR

**Comment by 0pcom** [comment]
> The issue was fixed recently. prob not updated in the AUR

but the `-git` package should build the latest commits, no?

**Comment by 0pcom** [comment]
> That's right. I never updated the tool, yet the problem has popped up. The issue lays in in [soundcloud API wrapper used by the tool ](https://github.com/7x11x13/soundcloud.py). Sadly the Moderator is mega cucked to update it or even merge PRs so look out for my fork I will try to fix. Seems Soundcloud changed something there end.

let me know if you want me to maintain that in the AUR for you ;)

**Comment by adithayyil** [comment]
> > The issue was fixed recently. prob not updated in the AUR
> 
> 
> 
> but the `-git` package should build the latest commits, no?

i don't think so, that one hasn't been updated since 2023-11-16. but from what i see, there is also
https://aur.archlinux.org/packages/soundcloud-dl which is up to date.

**Comment by 0pcom** [comment]
> > > The issue was fixed recently. prob not updated in the AUR
> > 
> > 
> > but the `-git` package should build the latest commits, no?
> 
> i don't think so, that one hasn't been updated since 2023-11-16. but from what i see, there is also https://aur.archlinux.org/packages/soundcloud-dl which is up to date.

unless there are changes to the actual packaging structure, the `-git` package should always build to the latest commits.

also, despite the fact that the non-git package was updated, I'm still getting the same error.


```
$ yay -S soundcloud-dl
AUR Explicit (1): soundcloud-dl-2.7.5-1
:: PKGBUILD up to date, skipping download: soundcloud-dl
  1 soundcloud-dl                    (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 soundcloud-dl                    (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: soundcloud-dl 2.7.5-1 (Tue 26 Mar 2024 09:49:20 AM CDT)
==> Retrieving sources...
  -> Found soundcloud-dl-2.7.5.tag.gz
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    soundcloud-dl-2.7.5.tag.gz ... Passed
:: (1/1) Parsing SRCINFO: soundcloud-dl
==> Making package: soundcloud-dl 2.7.5-1 (Tue 26 Mar 2024 09:49:20 AM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found soundcloud-dl-2.7.5.tag.gz
==> Validating source files with sha256sums...
    soundcloud-dl-2.7.5.tag.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting soundcloud-dl-2.7.5.tag.gz with bsdtar
==> Sources are ready.
==> Making package: soundcloud-dl 2.7.5-1 (Tue 26 Mar 2024 09:49:22 AM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
* Getting build dependencies for wheel...
/usr/lib/python3.11/site-packages/setuptools/dist.py:314: InformationOnly: Normalizing 'v2.7.5' to '2.7.5'
  self.metadata.version = self._normalize_version(self.metadata.version)
running egg_info
creating scdl.egg-info
writing scdl.egg-info/PKG-INFO
writing dependency_links to scdl.egg-info/dependency_links.txt
writing entry points to scdl.egg-info/entry_points.txt
writing requirements to scdl.egg-info/requires.txt
writing top-level names to scdl.egg-info/top_level.txt
writing manifest file 'scdl.egg-info/SOURCES.txt'
reading manifest file 'scdl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
adding license file 'AUTHORS'
writing manifest file 'scdl.egg-info/SOURCES.txt'
* Building wheel...
/usr/lib/python3.11/site-packages/setuptools/dist.py:314: InformationOnly: Normalizing 'v2.7.5' to '2.7.5'
  self.metadata.version = self._normalize_version(self.metadata.version)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/scdl
copying scdl/scdl.py -> build/lib/scdl
copying scdl/utils.py -> build/lib/scdl
copying scdl/__init__.py -> build/lib/scdl
running egg_info
writing scdl.egg-info/PKG-INFO
writing dependency_links to scdl.egg-info/dependency_links.txt
writing entry points to scdl.egg-info/entry_points.txt
writing requirements to scdl.egg-info/requires.txt
writing top-level names to scdl.egg-info/top_level.txt
reading manifest file 'scdl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
adding license file 'AUTHORS'
writing manifest file 'scdl.egg-info/SOURCES.txt'
copying scdl/scdl.cfg -> build/lib/scdl
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/scdl
copying build/lib/scdl/scdl.py -> build/bdist.linux-x86_64/wheel/scdl
copying build/lib/scdl/utils.py -> build/bdist.linux-x86_64/wheel/scdl
copying build/lib/scdl/scdl.cfg -> build/bdist.linux-x86_64/wheel/scdl
copying build/lib/scdl/__init__.py -> build/bdist.linux-x86_64/wheel/scdl
running install_egg_info
Copying scdl.egg-info to build/bdist.linux-x86_64/wheel/scdl-2.7.5-py3.11.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/scdl-2.7.5.dist-info/WHEEL
creating '/home/user/.cache/yay/soundcloud-dl/src/scdl-2.7.5/dist/.tmp-g_8ts7au/scdl-2.7.5-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'scdl/__init__.py'
adding 'scdl/scdl.cfg'
adding 'scdl/scdl.py'
adding 'scdl/utils.py'
adding 'scdl-2.7.5.dist-info/AUTHORS'
adding 'scdl-2.7.5.dist-info/LICENSE'
adding 'scdl-2.7.5.dist-info/METADATA'
adding 'scdl-2.7.5.dist-info/WHEEL'
adding 'scdl-2.7.5.dist-info/entry_points.txt'
adding 'scdl-2.7.5.dist-info/top_level.txt'
adding 'scdl-2.7.5.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built scdl-2.7.5-py3-none-any.whl
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "soundcloud-dl"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: soundcloud-dl 2.7.5-1 (Tue 26 Mar 2024 09:49:24 AM CDT)
==> Cleaning up...
loading packages...
resolving dependencies...
looking for conflicting packages...

Package (1)    New Version  Net Change

soundcloud-dl  2.7.5-1        0.18 MiB

Total Installed Size:  0.18 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                        [--------------------------------------] 100%
(1/1) checking package integrity                                      [--------------------------------------] 100%
(1/1) loading package files                                           [--------------------------------------] 100%
(1/1) checking for file conflicts                                     [--------------------------------------] 100%
:: Processing package changes...
(1/1) installing soundcloud-dl                                        [--------------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[user@linux Music]$ cd kind
[user@linux kind]$ scdl -l https://soundcloud.com/kind/begin-again-kindtide-flip
Soundcloud Downloader
Traceback (most recent call last):
  File "/usr/bin/scdl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/scdl/scdl.py", line 158, in main
    if not client.is_client_id_valid():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/soundcloud/soundcloud.py", line 125, in is_client_id_valid
    next(
StopIteration

```

![image](https://github.com/flyingrub/scdl/assets/36607567/e8d95adf-36b1-4c6f-8fa3-2d4de8288b4f)

**Comment by 7x11x13** [comment]
I don't know anything about how AUR handles dependency versions, perhaps the version of python-soundcloud-v2 you have was not upgraded when you updated to the latest scdl version?

**Comment by 0pcom** [comment]
> I don't know anything about how AUR handles dependency versions, perhaps the version of python-soundcloud-v2 you have was not upgraded when you updated to the latest scdl version? I believe the error shown is only possible in old versions ( <1.3.7 ) of soundcloud-v2

right you are, updating python-soundcloud-v2 solved it, thanks. I'll close this now.
